[tox]
envlist = html
skipsdist = true

[testenv]
deps =
    -r requirements/build.txt

[testenv:html]
commands =
    sphinx-build -E -W --keep-going -b html src build/html -j auto

[testenv:autobuild]
commands =
    sphinx-autobuild -E -W --keep-going -b html src build/html -j auto --port 0 --ignore "*.swp"
